services:
  iut_service:
    container_name: iut_service
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api:/usr/src/app
    ports:
      - 3333:3000
    #command: bash -c "npm i && npm start"
    command: npm run watch
    networks:
      - iut

networks:
  iut:
    driver: bridge